# Training Configuration

# Data
data:
  batch_size: 64
  num_workers: 4
  pin_memory: true
  validation_split: 0.1  # 10% of training data for validation

# Training
training:
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001

  # Optimizer
  optimizer:
    name: "adam"
    betas: [0.9, 0.999]
    eps: 1.0e-08

  # Learning rate scheduler
  scheduler:
    name: "step_lr"
    step_size: 10
    gamma: 0.1

  # Early stopping
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001

  # Gradient clipping
  gradient_clipping:
    enabled: true
    max_norm: 1.0

# Device
device:
  use_cuda: true  # Use GPU if available
  cuda_device: 0  # GPU device number

# Random seed for reproducibility
seed: 42

# Logging
logging:
  log_interval: 10  # Log every N batches
  tensorboard: true
  mlflow: true

# Experiment tracking
experiment:
  name: "quantum-mnist-hybrid"
  tags:
    - "quantum"
    - "hybrid"
    - "mnist"
    - "resnet18"
    - "pennylane"
